#!/usr/bin/env bash

set -eu

readonly THIS_CMD="${0##*/}"
readonly VERSION="v0.0.1"
readonly URI='https://websh.jiro4989.com/api/shellgei'

_main() {

    if (($# < 1)); then
        _help
        return
    fi

    result=$(_post "$*")

    # 標準出力を表示
    jq -r '.stdout' <<< "$result"

    # 標準エラー出力があれば表示
    stderr="$(jq -r '.stderr' <<< "$result")"
    if [ -n "$stderr" ]
    then
        _err "$stderr"
    fi

    # 詳細情報を表示
    status="$(jq -r '.status' <<< "$result")"
    _info "status: $status"
    system_message="$(jq -r '.system_message' <<< "$result")"
    _info "system_message: $system_message"
    elapsed_time="$(jq -r '.elapsed_time' <<< "$result")"
    _info "elapsed_time: $elapsed_time"
}

_help() {
cat << EOS
Execute commands on ShellgeiBot using websh API

USAGE:
    $THIS_CMD -h | --help
    $THIS_CMD -V | --version
    $THIS_CMD [OPTIONS] CODE
    echo CODE | $THIS_CMD [OPTIONS] CODE

EXAMPLES:
    $THIS_CMD 'echo hello'
    echo 'echo hello' | $THIS_CMD
    $THIS_CMD 'screenfetch | textimg -s'

OPTIONS:
    -h --help                   Display this help and exit
    -V --version                Display this version and exit
    -v --verbose                Show detail information

EOS
}

_err() {
    echo -e "[ \e[31mERR\e[m ] "$*" " >&2
}

_info() {
    echo -e "[ \e[36mINFO\e[m ] $*" >&2
}

_post() {
    local code="${*}"
    local body="{
        \"code\": \"$code\",
        \"images\": []
    }"

    curl --silent --request POST --data "$body" $URI
}

_main "$@"
exit $?
